name = ""
license = "Apache-2.0"
licenselink = ""
description = ""

# The home page of the theme, where the source can be found.
homepage = ""

# If you have a running demo of the theme.
demosite = ""


# If the theme has a single author
[author]
    name = ""
    homepage = ""

# If porting an existing theme
[original]
  name = "Jeremy Nusser"
  homepage = "https://nusserstudios.com"
  repo = "https://github.com/nusserstudios/tailbliss"
